// Generated by LiveScript 1.2.0
var blessed, fs, screen, log, line, textbox, doLog;
blessed = require('blessed');
fs = require('fs');
screen = blessed.screen();
log = blessed.box({
  parent: screen,
  scrollable: true,
  alwaysScroll: true,
  vi: true,
  top: 0,
  bottom: 2
});
line = blessed.line({
  parent: screen,
  orientation: 'horizontal',
  bottom: 1
});
textbox = blessed.textbox({
  parent: screen,
  keys: false,
  height: 1,
  bottom: 0,
  style: {
    fg: 'white'
  }
});
doLog = function(it){
  log.pushLine(it);
  log.setScrollPerc(100);
};
screen.append(log);
screen.append(line);
screen.append(textbox);
screen.key(['q', 'C-c'], function(){
  return process.exit(0);
});
screen.key('i', function(){
  textbox.readInput(function(){});
});
screen.key('e', function(){
  textbox.readEditor(function(){});
});
screen.key('j', function(){
  log.scroll(10);
  screen.render();
});
screen.key('k', function(){
  log.scroll(-10);
  screen.render();
});
screen.key('S-j', function(){
  log.scroll(1);
  screen.render();
});
screen.key('S-k', function(){
  log.scroll(-1);
  screen.render();
});
textbox.on('submit', function(it){
  doLog(it);
  textbox.clearValue();
  textbox.readInput(function(){});
  screen.render();
});
textbox.readInput(function(){});
fs.readFile('init.txt', function(err, data){
  if (err) {
    return;
  }
  log.pushLine(data + "");
  log.setScrollPerc(100);
  screen.render();
});
screen.render();