// Generated by LiveScript 1.2.0
var fs, dir, log, readFile, fifoReader, fifoWriter, init;
fs = require('fs');
dir = '';
log = null;
readFile = function(filename, callback){
  fs.readFile(dir + filename, function(err, data){
    if (err) {
      throw err;
    } else {
      callback(data);
    }
  });
};
fifoReader = function(filename){
  return function(callback){
    var stream;
    stream = fs.createReadStream(filename);
    stream.on('data', callback);
  };
};
fifoWriter = function(filename){
  var stream;
  stream = fs.createWriteStream(filename);
  return function(it){
    stream.write(it + "\n");
  };
};
init = function(ratoxDir, doLog, callback){
  dir = ratoxDir + "/";
  log = doLog;
  readFile('../name/out', function(name){
    module.exports.nameOwn = (name + "").trim();
    readFile('name', function(name){
      module.exports.nameFriend = (name + "").trim();
      module.exports.textIn = fifoReader(dir + 'text_out');
      module.exports.textOut = fifoWriter(dir + 'text_in');
      delete module.exports.init;
      callback();
    });
  });
};
module.exports = {
  init: init
};