// Generated by LiveScript 1.2.0
var fs, tail, init;
fs = require('fs');
tail = require('tail');
init = function(dir, log, callback){
  var readFile;
  dir += '/';
  readFile = function(filename, callback){
    fs.readFile(dir + filename, function(err, data){
      if (err) {
        throw err;
      } else {
        callback(data);
      }
    });
  };
  readFile('../name/out', function(name){
    module.exports.nameOwn = (name + "").trim();
    readFile('name', function(name){
      var textIn, stream;
      module.exports.nameFriend = (name + "").trim();
      textIn = new tail.Tail(dir + 'text_out', '\n', {
        persistent: false
      });
      module.exports.textIn = function(callback){
        textIn.on('line', callback);
      };
      stream = fs.createWriteStream(dir + 'text_in');
      module.exports.textOut = function(it){
        stream.write(it + "\n");
      };
      delete module.exports.init;
      callback();
    });
  });
};
module.exports = {
  init: init
};